# Generated by Django 3.1.1 on 2021-07-08 23:14

from django.db import migrations, models
import encrypted_fields.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210708_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cc2_cvv',
            field=models.CharField(blank=True, max_length=6, verbose_name='CC2 CVV'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc2_exp_mo',
            field=models.CharField(blank=True, max_length=2, verbose_name='CC2 exp month'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc2_exp_yr',
            field=models.CharField(blank=True, max_length=4, verbose_name='CC2 exp year'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc2_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='CC2 number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc2_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='CC2 contact phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_cvv',
            field=models.CharField(blank=True, max_length=6, verbose_name='CC1 CVV'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_exp_mo',
            field=models.CharField(blank=True, max_length=2, verbose_name='CC1 exp month'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_exp_yr',
            field=models.CharField(blank=True, max_length=4, verbose_name='CC1 exp year'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='CC1 number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='CC1 contact phone'),
        ),
    ]
