# Generated by Django 3.1.1 on 2021-07-09 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210709_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ban',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Registration IP'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Registration latitude'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='registration_long',
            field=models.FloatField(blank=True, null=True, verbose_name='Registration longitude'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be allowed to login. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to the admin and backoffice sites.'),
        ),
    ]
