# Generated by Django 3.1.1 on 2021-07-09 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210709_0222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_deleted',
        ),
    ]
