# Generated by Django 3.1.1 on 2021-07-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_user_date_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_old',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
