# Generated by Django 3.1.1 on 2021-07-15 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_customer_id_old'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='discount',
            new_name='discount_pct',
        ),
    ]
