# Generated by Django 3.1.1 on 2021-07-22 02:06

from django.db import migrations, models
import encrypted_fields.fields
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210714_2207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='address_line_1',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_cvv',
            field=models.CharField(max_length=6, verbose_name='CC1 CVV'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_exp_mo',
            field=models.CharField(max_length=2, verbose_name='CC1 exp month'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_exp_yr',
            field=models.CharField(max_length=4, verbose_name='CC1 exp year'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_number',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='CC1 number'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cc_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='CC1 contact phone'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='customer',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=localflavor.us.models.USStateField(max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='zip',
            field=localflavor.us.models.USZipCodeField(max_length=10),
        ),
    ]
