# Generated by Django 3.1.1 on 2021-07-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210721_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_last_activity',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
