# Generated by Django 3.1.1 on 2021-08-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_user_admin_last_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='id_old',
        ),
    ]
