# Generated by Django 3.1.1 on 2021-08-10 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Reservations'), (3, 'Maintenance'), (4, 'Marketing'), (5, 'BBS Only')], default=5),
        ),
    ]
