# Generated by Django 3.1.1 on 2021-08-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_employee_access_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.IntegerField(choices=[(1, 'Employed'), (2, 'Suspended'), (3, 'Fired'), (4, 'Quit')], default=1),
        ),
    ]
