# Generated by Django 3.1.1 on 2021-08-18 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210815_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_backoffice',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to the backoffice site.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False, help_text='Designates whether this user has access to the admin site.'),
        ),
    ]
