# Generated by Django 3.1.1 on 2021-12-23 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210817_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_orig',
            field=models.IntegerField(null=True),
        ),
    ]
