# Generated by Django 3.1.1 on 2022-01-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20211230_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
