# Generated by Django 3.1.1 on 2022-01-02 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_customer_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='drivers_club',
            field=models.IntegerField(blank=True, choices=[(0, 'No'), (1, 'Silver'), (2, 'Gold'), (3, 'Platinum')], null=True),
        ),
    ]
