# Generated by Django 3.1.1 on 2022-01-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220102_0744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='no_email',
        ),
        migrations.AddField(
            model_name='customer',
            name='receive_email',
            field=models.BooleanField(default=True),
        ),
    ]
