# Generated by Django 3.1.1 on 2022-01-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20220102_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='music_favorite',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
