# Generated by Django 3.1.1 on 2022-01-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customer_music_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hired_on',
        ),
    ]
