# Generated by Django 3.1.1 on 2022-01-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_remove_employee_hired_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='driver_skill',
            field=models.IntegerField(blank=True, choices=[(0, '1 - Good lord.'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10 - Schumi')], null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, '1 - Horrible'), (1, '2'), (2, '3'), (3, '4'), (4, '5'), (5, '6'), (6, '7'), (7, '8'), (8, '9'), (9, '10 - Awesome')], null=True),
        ),
    ]
