# Generated by Django 3.1.1 on 2022-01-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_customer_stripe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='stripe_id',
            new_name='stripe_customer',
        ),
    ]
