# Generated by Django 3.1.1 on 2022-01-20 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20220114_2239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='card_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='card_2',
        ),
    ]
