# Generated by Django 4.0.3 on 2023-01-15 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_customer_cc2_phone_alter_customer_cc_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card_1_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='card_2_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
