# Generated by Django 3.1.1 on 2021-06-21 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField()),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Road Car'), ('bike', 'Bike'), ('track', 'Track Car')], max_length=20)),
                ('plate', models.CharField(blank=True, max_length=10)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('damage', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('policy_number_encrypted', models.CharField(blank=True, max_length=255)),
                ('policy_company', models.CharField(blank=True, max_length=255)),
                ('policy_phone', models.CharField(blank=True, max_length=30)),
                ('weighting', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('year',),
            },
        ),
    ]
