# Generated by Django 3.1.1 on 2021-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_vehicle_redirect_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Building'), (1, 'Ready'), (2, 'Damaged / Repairing'), (3, 'Out Of Service')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
