# Generated by Django 3.1.1 on 2021-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_auto_20210707_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='relinquished_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
