# Generated by Django 3.1.1 on 2021-07-07 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_auto_20210707_1532'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
