# Generated by Django 3.1.1 on 2021-08-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0009_bbspost_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
