# Generated by Django 3.1.1 on 2022-01-05 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0011_auto_20220104_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='bbspost',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
