# Generated by Django 3.1.1 on 2020-09-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Car'), ('bike', 'Bike')], max_length=20)),
            ],
        ),
    ]
