# Generated by Django 3.1.1 on 2020-10-07 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20200923_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='acquired_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
