# Generated by Django 3.1.1 on 2021-12-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_auto_20211223_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
