# Generated by Django 3.1.1 on 2021-12-26 20:57

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='newslettersubscription',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='email',
            field=users.models.LowercaseEmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='hash',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newslettersubscription',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
