# Generated by Django 3.1.1 on 2021-12-27 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_auto_20211226_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='full_name',
            field=models.CharField(max_length=255),
        ),
    ]
