# Generated by Django 3.1.1 on 2021-12-27 20:29

from django.db import migrations
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_auto_20211226_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettersubscription',
            name='email',
            field=users.models.LowercaseEmailField(max_length=254, null=True, unique=True),
        ),
    ]
