# Generated by Django 3.1.1 on 2022-01-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_sitecontent_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitecontent',
            name='id',
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='page',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
