# Generated by Django 3.1.1 on 2022-01-14 20:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20220113_1608'),
        ('marketing', '0010_auto_20220112_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='email_frequency',
            field=models.IntegerField(choices=[(5, 'Very often'), (4, 'A few times per month'), (3, 'Every month'), (2, 'A few times per year'), (1, 'Rarely or not at all')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='general_rating',
            field=models.IntegerField(choices=[(5, 'Awesome!'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='heard_about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='new_vehicles',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='pricing',
            field=models.IntegerField(choices=[(5, 'Excellent Value'), (4, 'Good Value'), (3, 'Average'), (2, 'Somewhat High'), (1, 'Very High'), (0, 'No experience with other firms')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='rental_frequency',
            field=models.IntegerField(choices=[(4, '10+'), (3, '5-10'), (2, '2-5'), (1, 'This was my first')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='vehicle_rating',
            field=models.IntegerField(choices=[(5, 'Awesome!'), (4, 'Good'), (3, 'Average'), (2, 'Fair'), (1, 'Poor')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='vehicle_types',
            field=models.IntegerField(choices=[(7, 'Exotics (Ferrari, Lamborghini, etc)'), (6, 'Race Cars (Track Driving)'), (5, 'Sports Cars (Lotus, Corvette, etc)'), (4, 'Grand Touring Cars'), (3, 'Performance Luxury Cars'), (2, 'Muscle Cars'), (1, 'Modified/Custom Cars'), (8, 'Sportbikes'), (9, 'Touring bikes'), (10, 'Cruising bikes'), (11, 'Off-road bikes/Supermoto/Adventure')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='surveyresponse',
            name='would_recommend',
            field=models.IntegerField(choices=[(3, 'Yes'), (2, 'Maybe'), (1, 'No')], default=1),
            preserve_default=False,
        ),
    ]
