# Generated by Django 3.1.1 on 2022-01-17 19:31

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_auto_20220114_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height', null=True, upload_to=marketing.models.get_email_image_path, width_field='width')),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
