# Generated by Django 3.1.1 on 2022-01-20 15:38

from django.db import migrations, models
import marketing.models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_emailimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailimage',
            name='image',
            field=models.ImageField(default='', height_field='height', upload_to=marketing.models.get_email_image_path, width_field='width'),
            preserve_default=False,
        ),
    ]
