# Generated by Django 3.1.1 on 2022-01-20 15:38

from django.conf import settings
from django.db import migrations, models
from django.contrib.sites.models import Site
import marketing.models


def set_site_name(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    initial_site = Site.objects.all().first()
    initial_site.domain = 'performancerentals.us'
    initial_site.name = 'Performance Rentals'
    initial_site.save()


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0013_auto_20220120_1038'),
    ]

    operations = [
        migrations.RunPython(set_site_name, reverse_code=migrations.RunPython.noop),
    ]
