# Generated by Django 4.0.3 on 2022-12-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_set_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='subject',
            field=models.CharField(max_length=255),
        ),
    ]
