# Generated by Django 4.0.3 on 2023-08-18 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_alter_newslettersubscription_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tweet',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='username',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
