# Generated by Django 3.1.1 on 2020-09-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='year',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
