# Generated by Django 3.1.1 on 2020-11-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_auto_20201007_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Road Car'), ('bike', 'Bike'), ('track', 'Track Car')], max_length=20),
        ),
    ]
