# Generated by Django 3.1.1 on 2021-06-21 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_auto_20201121_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='vehicle_type',
        ),
    ]
