# Generated by Django 3.1.1 on 2021-06-24 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_remove_vehicle_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='backoffice_vehicle_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
