# Generated by Django 3.1.1 on 2021-07-07 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_auto_20210624_0221'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='make',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='model',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='status',
            field=models.CharField(blank=True, choices=[(0, 'Building'), (1, 'Ready'), (2, 'Damaged / Repairing'), (3, 'Out Of Service')], max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('car', 'Road Car'), ('bike', 'Bike'), ('track', 'Track Car')], max_length=20),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
