# Generated by Django 3.1.1 on 2021-07-07 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0014_auto_20210707_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Building'), (1, 'Ready'), (2, 'Damaged / Repairing'), (3, 'Out Of Service')]),
        ),
    ]
