# Generated by Django 3.1.1 on 2021-07-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0016_auto_20210707_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='specs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='vehicle_id',
            field=models.IntegerField(blank=True, help_text='ID of backoffice Vehicle object this corresponds to', null=True),
        ),
    ]
