# Generated by Django 3.1.1 on 2021-07-07 16:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0017_auto_20210707_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='origin_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='specs',
            field=models.JSONField(blank=True, help_text='JSON format', null=True),
        ),
    ]
