# Generated by Django 3.1.1 on 2021-07-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0018_auto_20210707_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='deposit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='discount_2_day',
            field=models.IntegerField(blank=True, help_text='Percent', null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='discount_3_day',
            field=models.IntegerField(blank=True, help_text='Percent', null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='discount_7_day',
            field=models.IntegerField(blank=True, help_text='Percent', null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='miles_included',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
