# Generated by Django 3.1.1 on 2021-07-07 19:14

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0019_auto_20210707_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='discount_2_day',
            field=models.IntegerField(blank=True, help_text='Percent', null=True, verbose_name='2-day discount'),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='discount_3_day',
            field=models.IntegerField(blank=True, help_text='Percent', null=True, verbose_name='3-day discount'),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='discount_7_day',
            field=models.IntegerField(blank=True, help_text='Percent', null=True, verbose_name='7-day discount'),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='miles_included',
            field=models.IntegerField(blank=True, help_text='Per day', null=True),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='vehicle_id',
            field=models.IntegerField(blank=True, help_text='ID of Vehicle object this corresponds to', null=True),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(blank=True, max_length=255)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('car', 'Road Car'), ('bike', 'Bike'), ('track', 'Track Car')], max_length=20)),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Building'), (1, 'Ready'), (2, 'Damaged / Repairing'), (3, 'Out Of Service')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acquired_on', models.DateField(blank=True, null=True)),
                ('relinquished_on', models.DateField(blank=True, null=True)),
                ('plate', models.CharField(blank=True, max_length=10)),
                ('vin', models.CharField(blank=True, max_length=50)),
                ('mileage', models.IntegerField(blank=True, null=True)),
                ('damage', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('policy_number', encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255)),
                ('policy_company', models.CharField(blank=True, max_length=255)),
                ('policy_phone', models.CharField(blank=True, max_length=30)),
                ('weighting', models.IntegerField(blank=True, null=True)),
                ('redirect_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'ordering': ('year',),
            },
        ),
    ]
