# Generated by Django 3.1.1 on 2021-07-07 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_tolltag_vehiclepicture_vehiclevideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclepicture',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclepicture',
            name='image',
            field=models.ImageField(blank=True, height_field='height', upload_to='', width_field='width'),
        ),
        migrations.AddField(
            model_name='vehiclepicture',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclepicture',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='vehiclepicture',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
