# Generated by Django 3.1.1 on 2021-07-07 23:02

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_auto_20210707_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclepicture',
            name='image',
            field=models.ImageField(blank=True, height_field='height', upload_to=fleet.models.get_vehicle_picture_path, width_field='width'),
        ),
    ]
