# Generated by Django 3.1.1 on 2021-07-08 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_auto_20210707_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclepicture',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='vehiclepicture',
            name='vehicle_marketing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.vehiclemarketing'),
        ),
    ]
