# Generated by Django 3.1.1 on 2021-07-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_vehiclemarketing_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='weighting',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
