# Generated by Django 3.1.1 on 2021-07-11 16:36

from django.db import migrations, models
import django.db.models.deletion
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_vehiclemarketing_weighting'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='showcase_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='showcase_image',
            field=models.ImageField(blank=True, height_field='showcase_height', upload_to=fleet.models.get_vehicle_picture_path, width_field='showcase_width'),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='showcase_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiclepicture',
            name='vehicle_marketing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pics', to='fleet.vehiclemarketing'),
        ),
    ]
