# Generated by Django 3.1.1 on 2021-07-12 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0028_auto_20210711_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='id_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='status',
            field=models.IntegerField(choices=[(0, 'Building'), (1, 'Ready'), (2, 'Damaged / Repairing'), (3, 'Out Of Service')], default=0),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Road Car'), ('bike', 'Bike'), ('track', 'Track Car')], max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='status',
            field=models.IntegerField(choices=[(0, 'Building'), (1, 'Ready'), (2, 'Damaged / Repairing'), (3, 'Out Of Service')], default=0),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='vehicle_type',
            field=models.CharField(choices=[('car', 'Road Car'), ('bike', 'Bike'), ('track', 'Track Car')], max_length=20),
        ),
    ]
