# Generated by Django 3.1.1 on 2021-07-13 02:52

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_auto_20210712_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='policy_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
