# Generated by Django 3.1.1 on 2021-07-19 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0030_auto_20210712_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehiclemarketing',
            old_name='deposit',
            new_name='security_deposit',
        ),
    ]
