# Generated by Django 3.1.1 on 2021-07-26 13:13

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_auto_20210719_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='showcase_image',
            field=models.ImageField(blank=True, height_field='showcase_height', null=True, upload_to=fleet.models.get_vehicle_picture_path, width_field='showcase_width'),
        ),
    ]
