# Generated by Django 3.1.1 on 2021-07-27 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0002_auto_20210727_1311'),
        ('fleet', '0032_auto_20210726_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='external_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consignment.consigner'),
        ),
    ]
