# Generated by Django 3.1.1 on 2021-07-30 20:43

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_vehicle_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='thumbnail_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='thumbnail_image',
            field=models.ImageField(blank=True, height_field='thumbnail_height', null=True, upload_to=fleet.models.get_vehicle_picture_path, width_field='thumbnail_width'),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='thumbnail_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
