# Generated by Django 3.1.1 on 2021-07-31 23:57

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0035_auto_20210730_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='inspection_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='inspection_image',
            field=models.ImageField(blank=True, height_field='inspection_height', null=True, upload_to=fleet.models.get_vehicle_picture_path, width_field='inspection_width'),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='inspection_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
