# Generated by Django 3.1.1 on 2021-08-04 11:30

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0036_auto_20210731_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclemarketing',
            name='mobile_thumbnail_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='mobile_thumbnail_image',
            field=models.ImageField(blank=True, height_field='mobile_thumbnail_height', null=True, upload_to=fleet.models.get_vehicle_picture_path, width_field='mobile_thumbnail_width'),
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='mobile_thumbnail_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
