# Generated by Django 3.1.1 on 2021-08-04 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0038_auto_20210804_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Road Car'), (2, 'Bike'), (3, 'Track Car')], default=1),
        ),
    ]
