# Generated by Django 3.1.1 on 2021-12-25 16:34

from django.db import migrations, models
import django.db.models.deletion
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0040_remove_vehicle_id_old'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclepicture',
            options={'ordering': ('-is_first',)},
        ),
        migrations.AddField(
            model_name='vehiclemarketing',
            name='id_orig',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='is_first',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='thumb_extension',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='thumb_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='thumb_width',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='thumbnail',
            field=models.ImageField(blank=True, height_field='thumb_height', upload_to=fleet.models.get_vehicle_picture_path, width_field='thumb_width'),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='vehicle_marketing',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vids', to='fleet.vehiclemarketing'),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='video',
            field=models.FileField(blank=True, upload_to=fleet.models.get_vehicle_video_path),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Road Car'), (2, 'Motorcycle'), (3, 'Track Car')], default=1),
        ),
        migrations.AlterField(
            model_name='vehiclemarketing',
            name='vehicle_type',
            field=models.IntegerField(choices=[(1, 'Road Car'), (2, 'Motorcycle'), (3, 'Track Car')], default=1),
        ),
    ]
