# Generated by Django 3.1.1 on 2021-12-25 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0041_auto_20211225_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemarketing',
            name='id_orig',
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='file_extension',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
