# Generated by Django 3.1.1 on 2021-12-26 14:49

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0042_auto_20211225_1148'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiclevideo',
            options={'ordering': ('-is_first',)},
        ),
        migrations.RenameField(
            model_name='vehiclevideo',
            old_name='video',
            new_name='video_mp4',
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='video_webm',
            field=models.FileField(blank=True, upload_to=fleet.models.get_vehicle_video_path),
        ),
    ]
