# Generated by Django 3.1.1 on 2021-12-26 14:59

from django.db import migrations, models
import fleet.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0043_auto_20211226_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclevideo',
            name='poster',
            field=models.ImageField(blank=True, height_field='poster_height', upload_to=fleet.models.get_vehicle_picture_path, width_field='poster_width'),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='poster_height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehiclevideo',
            name='poster_width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
