# Generated by Django 3.1.1 on 2022-01-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0045_auto_20211230_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclemarketing',
            name='vehicle_id',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_marketing_id',
            field=models.IntegerField(blank=True, help_text='ID of VehicleMarketing object this corresponds to', null=True),
        ),
    ]
