# Generated by Django 3.1.1 on 2021-07-27 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consignment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consigner',
            name='account_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consigner',
            name='address',
            field=encrypted_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='consigner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consigner',
            name='first_name',
            field=models.CharField(default='', max_length=30, verbose_name='first name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consigner',
            name='id_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consigner',
            name='last_name',
            field=models.CharField(default='', max_length=30, verbose_name='last name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consigner',
            name='notes',
            field=encrypted_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='consigner',
            name='routing_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='consigner',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
