# Generated by Django 3.1.1 on 2021-07-28 02:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0034_vehicle_slug'),
        ('consignment', '0002_auto_20210727_1311'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsignmentVehicle',
        ),
        migrations.AddField(
            model_name='consignmentreservation',
            name='back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignmentreservation',
            name='out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consignmentreservation',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consignmentreservation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
    ]
