# Generated by Django 3.1.1 on 2021-07-28 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0003_auto_20210727_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentreservation',
            name='consigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consignment.consigner'),
        ),
    ]
