# Generated by Django 3.1.1 on 2022-01-11 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0005_remove_consigner_id_old'),
    ]

    operations = [
        migrations.AddField(
            model_name='consignmentpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='consignmentpayment',
            name='consigner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consignment.consigner'),
        ),
        migrations.AddField(
            model_name='consignmentpayment',
            name='method',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='consignmentpayment',
            name='paid_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
