# Generated by Django 3.1.1 on 2022-01-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consignment', '0006_auto_20220111_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
