# Generated by Django 4.0.3 on 2022-03-22 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0048_auto_20220109_2252'),
        ('consignment', '0007_auto_20220111_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consignmentreservation',
            name='back_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='consignmentreservation',
            name='consigner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consignment.consigner'),
        ),
        migrations.AlterField(
            model_name='consignmentreservation',
            name='out_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='consignmentreservation',
            name='vehicle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
    ]
