# Generated by Django 3.1.1 on 2021-07-12 23:46

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20210711_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='reservation',
            name='delivery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='delivery_zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='deposit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='drivers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='extra_miles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='miles_included',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Unconfirmed'), (1, 'Confirmed')], default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
