# Generated by Django 3.1.1 on 2021-07-13 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0029_auto_20210712_2357'),
        ('sales', '0005_auto_20210712_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
    ]
