# Generated by Django 3.1.1 on 2021-07-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_auto_20210713_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='id_old',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
