# Generated by Django 3.1.1 on 2021-07-13 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210712_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='discount',
            name='code',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discount',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
