# Generated by Django 3.1.1 on 2021-07-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_auto_20210715_0253'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=10)),
                ('country', models.CharField(default='us', max_length=20)),
                ('total_rate', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('detail', models.JSONField(blank=True)),
                ('date_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesTax',
        ),
    ]
