# Generated by Django 3.1.1 on 2021-07-20 15:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_auto_20210719_1535'),
        ('users', '0011_auto_20210714_2207'),
        ('sales', '0013_auto_20210719_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='notes',
            new_name='customer_notes',
        ),
        migrations.AddField(
            model_name='rental',
            name='abuse',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='back_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='rental',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AddField(
            model_name='rental',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='damage_in',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='damage_out',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rental',
            name='delivery_zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit_charged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='deposit_refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='drivers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='extended_days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='extra_miles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='id_old',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='internal_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='mileage_back',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='mileage_out',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='miles_included',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='rental_discount_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='reserved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rental',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Incomplete'), (1, 'Confirmed/Billed'), (2, 'In Progress'), (3, 'Complete'), (4, 'Cancelled')], default=0),
        ),
        migrations.AddField(
            model_name='rental',
            name='tax_percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle'),
        ),
    ]
