# Generated by Django 3.1.1 on 2021-07-20 15:53

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0031_auto_20210719_1535'),
        ('users', '0011_auto_20210714_2207'),
        ('sales', '0014_auto_20210720_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='back_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='delivery_required',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='delivery_zip',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='extra_miles',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='id',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='id_old',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='miles_included',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='out_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='reserved_at',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='rental',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='back_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='confirmation_code',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='delivery_required',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='delivery_zip',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='deposit_amount',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='extra_miles',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='id_old',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='miles_included',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='out_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reserved_at',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='tax_percent',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='vehicle',
        ),
        migrations.CreateModel(
            name='BaseReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_old', models.IntegerField(blank=True, null=True)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('out_at', models.DateTimeField(blank=True, null=True)),
                ('back_at', models.DateTimeField(blank=True, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('drivers', models.IntegerField(blank=True, null=True)),
                ('miles_included', models.IntegerField(blank=True, null=True)),
                ('extra_miles', models.IntegerField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('deposit_amount', models.IntegerField(blank=True, null=True)),
                ('confirmation_code', models.CharField(blank=True, max_length=10)),
                ('delivery_required', models.BooleanField(default=False)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('delivery_zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='basereservation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.basereservation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='basereservation_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.basereservation'),
            preserve_default=False,
        ),
    ]
