# Generated by Django 3.1.1 on 2021-07-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_auto_20210720_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basereservation',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
