# Generated by Django 3.1.1 on 2021-08-09 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_auto_20210721_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basereservation',
            name='id_old',
        ),
    ]
