# Generated by Django 3.1.1 on 2021-12-27 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_remove_basereservation_id_old'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('percent', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='percent',
        ),
        migrations.AddField(
            model_name='coupon',
            name='promotion_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='sales.promotion'),
            preserve_default=False,
        ),
    ]
