# Generated by Django 3.1.1 on 2021-12-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_auto_20211227_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='service_type',
            field=models.CharField(blank=True, choices=[('rental', 'Rental'), ('perfexp', 'Performance Experience'), ('joyride', 'Joy Ride')], max_length=50),
        ),
    ]
