# Generated by Django 3.1.1 on 2021-12-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_promotion_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='service_type',
            field=models.CharField(blank=True, choices=[('rental', 'Rental'), ('perfexp', 'Performance Experience'), ('joyride', 'Joy Ride'), ('giftcert', 'Gift Certificate')], max_length=50),
        ),
    ]
