# Generated by Django 3.1.1 on 2022-01-01 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_auto_20211227_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='basereservation',
            name='app_channel',
            field=models.CharField(blank=True, choices=[('web', 'Web'), ('mobile', 'Mobile'), ('phone', 'Phone')], default='web', max_length=20),
        ),
    ]
