# Generated by Django 3.1.1 on 2022-01-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_basereservation_app_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.IntegerField(choices=[(0, 'Unconfirmed'), (1, 'Confirmed')], default=0),
        ),
    ]
