# Generated by Django 3.1.1 on 2022-01-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_auto_20220101_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='basereservation',
            name='is_military',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basereservation',
            name='override_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
