# Generated by Django 3.1.1 on 2022-01-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_auto_20220101_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='background_check',
            field=models.BooleanField(default=False),
        ),
    ]
