# Generated by Django 3.1.1 on 2022-01-03 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_customer_music_favorite'),
        ('sales', '0025_rental_background_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='driver',
            name='rental',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sales.rental'),
            preserve_default=False,
        ),
    ]
