# Generated by Django 3.1.1 on 2022-01-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0026_auto_20220103_1548'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ('-is_primary',)},
        ),
    ]
