# Generated by Django 3.1.1 on 2022-01-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_auto_20220104_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='basereservation',
            name='final_price_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
