# Generated by Django 3.1.1 on 2022-01-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_auto_20220108_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='basereservation',
            name='type',
            field=models.CharField(blank=True, choices=[('reservation', 'Unconfirmed Reservation'), ('rental', 'Confirmed Rental')], default='reservation', max_length=20),
        ),
        migrations.AlterField(
            model_name='basereservation',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='basereservation',
            unique_together={('confirmation_code', 'type')},
        ),
    ]
