# Generated by Django 3.1.1 on 2022-01-10 12:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220104_1400'),
        ('fleet', '0048_auto_20220109_2252'),
        ('sales', '0031_auto_20220109_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='guideddrive',
            name='backup_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='big_and_tall',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer'),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='customer_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='event_type',
            field=models.IntegerField(blank=True, choices=[(1, 'Joy Ride'), (2, 'Performance Experience')], default=1),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='internal_notes',
            field=encrypted_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='num_drivers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='num_minors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='num_passengers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='requested_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Confirmed/Billed'), (2, 'Complete'), (3, 'Cancelled')], default=0),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='vehicle_choice_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='vehicle_choice_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='guideddrive',
            name='vehicle_choice_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='internal_notes',
            field=encrypted_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
