# Generated by Django 3.1.1 on 2022-01-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_auto_20220110_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideddrive',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
