# Generated by Django 3.1.1 on 2022-01-10 13:42

from django.db import migrations, models
import django.db.models.deletion
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220104_1400'),
        ('fleet', '0048_auto_20220109_2252'),
        ('sales', '0033_auto_20220110_0820'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoyRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Confirmed/Billed'), (2, 'Complete'), (3, 'Cancelled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_passengers', models.IntegerField(blank=True, null=True)),
                ('num_minors', models.IntegerField(blank=True, null=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('backup_date', models.DateField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', encrypted_fields.fields.EncryptedTextField(blank=True)),
                ('big_and_tall', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('event_type', models.IntegerField(blank=True, choices=[(1, 'Joy Ride'), (2, 'Performance Experience')], default=1)),
                ('confirmation_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
                ('vehicle_choice_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
                ('vehicle_choice_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
                ('vehicle_choice_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PerformanceExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Confirmed/Billed'), (2, 'Complete'), (3, 'Cancelled')], default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('num_passengers', models.IntegerField(blank=True, null=True)),
                ('num_minors', models.IntegerField(blank=True, null=True)),
                ('requested_date', models.DateField(blank=True, null=True)),
                ('backup_date', models.DateField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True)),
                ('internal_notes', encrypted_fields.fields.EncryptedTextField(blank=True)),
                ('big_and_tall', models.BooleanField(default=False)),
                ('coupon_code', models.CharField(blank=True, max_length=30)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('event_type', models.IntegerField(blank=True, choices=[(1, 'Joy Ride'), (2, 'Performance Experience')], default=1)),
                ('confirmation_code', models.CharField(blank=True, max_length=10, unique=True)),
                ('num_drivers', models.IntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.customer')),
                ('vehicle_choice_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
                ('vehicle_choice_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
                ('vehicle_choice_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='fleet.vehicle')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='GuidedDrive',
        ),
    ]
