# Generated by Django 3.1.1 on 2022-01-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_auto_20220110_2141'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joyride',
            old_name='rate',
            new_name='override_subtotal',
        ),
        migrations.RenameField(
            model_name='performanceexperience',
            old_name='rate',
            new_name='override_subtotal',
        ),
        migrations.RemoveField(
            model_name='basereservation',
            name='rate',
        ),
        migrations.AlterField(
            model_name='basereservation',
            name='override_subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
    ]
