# Generated by Django 3.1.1 on 2022-01-12 13:04

from django.db import migrations, models
import django.utils.timezone
import encrypted_fields.fields
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_auto_20220111_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcertificate',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='beneficiary_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_address',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_cvv',
            field=models.CharField(blank=True, max_length=6, verbose_name='CC1 CVV'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_exp_mo',
            field=models.CharField(blank=True, max_length=2, verbose_name='CC1 exp month'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_exp_yr',
            field=models.CharField(blank=True, max_length=4, verbose_name='CC1 exp year'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='CC1 number'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='CC1 contact phone'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='cc_zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='remarks',
            field=encrypted_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='tag',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='used_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='value_message',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
