# Generated by Django 3.1.1 on 2022-01-12 14:34

from django.db import migrations, models
import encrypted_fields.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_auto_20220112_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_cvv',
            field=models.CharField(blank=True, max_length=6, verbose_name='CC CVV'),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_exp_mo',
            field=models.CharField(blank=True, max_length=2, verbose_name='CC exp month'),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_exp_yr',
            field=models.CharField(blank=True, max_length=4, verbose_name='CC exp year'),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='CC number'),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='CC contact phone'),
        ),
    ]
