# Generated by Django 3.1.1 on 2022-01-13 12:42

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import encrypted_fields.fields
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_auto_20220112_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocpayment',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='cc_address',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='cc_city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='cc_cvv',
            field=models.CharField(blank=True, max_length=6, verbose_name='CC CVV'),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='cc_exp_mo',
            field=models.CharField(blank=True, max_length=2, verbose_name='CC exp month'),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='cc_exp_yr',
            field=models.CharField(blank=True, max_length=4, verbose_name='CC exp year'),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='cc_number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='CC number'),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='cc_state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='cc_zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='foreign_region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='full_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='item',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='CC contact phone'),
        ),
    ]
