# Generated by Django 3.1.1 on 2022-01-13 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_auto_20220113_0742'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocpayment',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
