# Generated by Django 3.1.1 on 2022-01-13 13:26

from django.db import migrations
import django_countries.fields
import sales.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_adhocpayment_submitted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocpayment',
            name='country',
            field=django_countries.fields.CountryField(blank=True, countries=sales.models.AllCountries, max_length=2),
        ),
    ]
