# Generated by Django 3.1.1 on 2022-01-14 19:31

from django.db import migrations, models
import localflavor.us.models
import phonenumber_field.modelfields
import sales.utils


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_auto_20220113_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('zip', localflavor.us.models.USZipCodeField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('license_number', models.CharField(blank=True, max_length=30)),
                ('license_state', localflavor.us.models.USStateField(blank=True, max_length=2)),
                ('ssn', sales.utils.EncryptedUSSocialSecurityNumberField(blank=True, max_length=11, null=True)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Ban',
        ),
    ]
