# Generated by Django 3.1.1 on 2022-01-14 19:33

from django.db import migrations
import encrypted_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_auto_20220114_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redflag',
            name='address',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
    ]
