# Generated by Django 3.1.1 on 2022-01-14 19:38

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_auto_20220114_1433'),
    ]

    operations = [
        migrations.RenameField(
            model_name='redflag',
            old_name='phone',
            new_name='home_phone',
        ),
        migrations.AddField(
            model_name='redflag',
            name='mobile_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
