# Generated by Django 3.1.1 on 2022-01-15 03:39

from django.db import migrations, models
import encrypted_fields.fields
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_auto_20220114_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='address',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(blank=True, max_length=6, verbose_name='CC CVV'),
        ),
        migrations.AddField(
            model_name='card',
            name='number',
            field=encrypted_fields.fields.EncryptedCharField(blank=True, max_length=255, verbose_name='CC number'),
        ),
        migrations.AddField(
            model_name='card',
            name='state',
            field=localflavor.us.models.USStateField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='zip',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
    ]
