# Generated by Django 3.1.1 on 2022-01-20 15:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0051_auto_20220114_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocpayment',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.card'),
        ),
        migrations.AddField(
            model_name='card',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='CC contact phone'),
        ),
        migrations.AddField(
            model_name='charge',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.card'),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.card'),
        ),
    ]
