# Generated by Django 3.1.1 on 2022-01-20 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0052_auto_20220120_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
