# Generated by Django 3.2.12 on 2022-02-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0053_card_is_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basereservation',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
