# Generated by Django 3.2.12 on 2022-03-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0054_alter_basereservation_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcertificate',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
