# Generated by Django 3.2.12 on 2022-03-14 01:55

from django.db import migrations, models
import encrypted_fields.fields
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0055_alter_giftcertificate_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcertificate',
            name='beneficiary_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_address',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_state',
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='cc_zip',
            field=localflavor.us.models.USZipCodeField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='giftcertificate',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
