# Generated by Django 4.0.3 on 2022-04-17 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0058_rename_cidr_ipban_prefix_bits'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocpayment',
            name='confirmation_code',
            field=models.CharField(blank=True, db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='basereservation',
            name='confirmation_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='joyride',
            name='confirmation_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='performanceexperience',
            name='confirmation_code',
            field=models.CharField(blank=True, db_index=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='service_type',
            field=models.CharField(blank=True, choices=[('rental', 'Rental'), ('perfexp', 'Performance Experience'), ('joyride', 'Joy Ride'), ('giftcert', 'Gift Certificate'), ('subpay', 'Ad-hoc Payment')], max_length=50),
        ),
    ]
