# Generated by Django 4.0.3 on 2022-04-23 20:49

from django.db import migrations, models
import encrypted_fields.fields
import localflavor.us.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0060_alter_adhocpayment_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adhocpayment',
            name='cc_address',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='cc_city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='cc_cvv',
            field=models.CharField(max_length=6, verbose_name='CC CVV'),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='cc_exp_mo',
            field=models.CharField(max_length=2, verbose_name='CC exp month'),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='cc_exp_yr',
            field=models.CharField(max_length=4, verbose_name='CC exp year'),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='cc_number',
            field=encrypted_fields.fields.EncryptedCharField(max_length=255, verbose_name='CC number'),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='cc_state',
            field=localflavor.us.models.USStateField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='cc_zip',
            field=localflavor.us.models.USZipCodeField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='adhocpayment',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='CC contact phone'),
        ),
    ]
