# Generated by Django 4.0.3 on 2023-01-11 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0048_auto_20220109_2252'),
        ('users', '0036_alter_customer_cc2_phone_alter_customer_cc_phone'),
        ('sales', '0063_alter_card_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basereservation',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.customer'),
        ),
        migrations.AlterField(
            model_name='basereservation',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fleet.vehicle'),
        ),
    ]
