# Generated by Django 4.0.3 on 2023-01-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0065_alter_ipban_prefix_bits'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
