# Generated by Django 4.0.3 on 2023-01-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0066_charge_stripe_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='adhocpayment',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='stripe_customer',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
