# Generated by Django 4.0.3 on 2023-01-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0067_adhocpayment_stripe_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='error_code',
        ),
        migrations.AddField(
            model_name='adhocpayment',
            name='card_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='charge',
            name='card_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='giftcertificate',
            name='card_status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
